### ISSUE TITLE
A.1.5 の mu_N を求めるコードに関して

### ISSUE THREAD

**Issue by yohpapa** [ryuichiueda/LNPR#1]
上田先生、はじめまして。
大変分かりやすくて楽しい書籍、ありがとうございます。先生の生徒さんがうらやましいです！

[gauss_gamma.ipynb](https://github.com/ryuichiueda/LNPR/blame/2224a4948b3e06e8e3e380dfe648ecddbd46acc1/inference/gauss_gamma.ipynb#L143) に関して質問させて下さい。
```
mu_N = 1.0/(N+beta_0)*sum(samples) + beta_0/(N+beta_0)*mu_0
```
書籍の内容からすると
```
mu_N = 1.0/(N+zeta_0)*sum(samples) + zeta_0/(N+zeta_0)*mu_0
```
が正しいように見えるのですが、いかがでしょうか？結果がさほど変わらないのであまり自信がなく、ご質問させて頂きました。

オリジナルの結果: mu_N == 207.14285714285714
修正の結果: mu_N == 208.33333333333331

**Comment by ryuichiueda** [comment]
お、ありがとうございます。すぐ手はつけられんのですが数日以内には検証します！

**Comment by ryuichiueda** [comment]
確認しました。ご指摘のとおりですー。これから訂正ページへの記載とコードの修正をします！

ありがとうございます

**Comment by ryuichiueda** [comment]
* 本リポジトリのコードの修正
* 書籍用のLNPR_BOOK_CODESの修正
* https://b.ueda.tech/?page=lnpr_typo への掲載

完了しました。ありがとうございました。
